---
kind: pipeline
name: audit modules

platform:
  os: linux
  arch: amd64

steps:
- name: install node:lts
  image: node:lts
  commands:
  - node --version
  - npm --version
  - yarn --version
  - yarn install
  - yarn run bootstrap
  depends_on:
  - clone

- name: audit all
  image: node:lts
  commands:
  - yarn run audit
  depends_on:
  - install node:lts

---
kind: pipeline
name: lint modules

platform:
  os: linux
  arch: amd64

steps:
- name: install node:lts
  image: node:lts
  commands:
  - node --version
  - npm --version
  - yarn --version
  - yarn install
  - yarn run bootstrap
  depends_on:
  - clone

- name: lint all
  image: node:lts
  commands:
  - yarn run lint
  depends_on:
  - install node:lts

---
kind: pipeline
name: size and timing

platform:
  os: linux
  arch: amd64

steps:
- name: slow-deps
  image: node:lts
  commands:
  - yarn global add slow-deps
  - slow-deps

---
kind: pipeline
name: SDK Core

platform:
  os: linux
  arch: amd64

steps:
- name: install node:6
  image: node:6
  commands:
  - node --version
  - npm --version
  - yarn --version
  - yarn install
  - yarn run bootstrap
  depends_on:
  - clone

- name: unit tests node:6
  image: node:6
  commands:
  - lerna run unit-test
  environment:
    BITGOJS_TEST_PASSWORD:
      from_secret: password
  depends_on:
  - install node:6

- name: upload coverage node:6
  image: node:6
  commands:
  - npm install -g codecov
  - yarn run gen-coverage
  - yarn run upload-coverage -- -F unit
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  depends_on:
  - unit tests node:6

- name: install node:8
  image: node:8
  commands:
  - node --version
  - npm --version
  - yarn --version
  - yarn install
  - yarn run bootstrap
  depends_on:
  - clone

- name: unit tests node:8
  image: node:8
  commands:
  - lerna run unit-test
  environment:
    BITGOJS_TEST_PASSWORD:
      from_secret: password
  depends_on:
  - install node:8

- name: upload coverage node:8
  image: node:8
  commands:
  - npm install -g codecov
  - yarn run gen-coverage
  - yarn run upload-coverage -- -F unit
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  depends_on:
  - unit tests node:8

- name: install node:10
  image: node:10
  commands:
  - node --version
  - npm --version
  - yarn --version
  - yarn install
  - yarn run bootstrap
  depends_on:
  - clone

- name: unit tests node:10
  image: node:10
  commands:
  - lerna run unit-test
  environment:
    BITGOJS_TEST_PASSWORD:
      from_secret: password
  depends_on:
  - install node:10

- name: upload coverage node:10
  image: node:10
  commands:
  - npm install -g codecov
  - yarn run gen-coverage
  - yarn run upload-coverage -- -F unit
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  depends_on:
  - unit tests node:10

- name: install node:11
  image: node:11
  commands:
  - node --version
  - npm --version
  - yarn --version
  - yarn install
  - yarn run bootstrap
  depends_on:
  - clone

- name: unit tests node:11
  image: node:11
  commands:
  - lerna run unit-test
  environment:
    BITGOJS_TEST_PASSWORD:
      from_secret: password
  depends_on:
  - install node:11

- name: upload coverage node:11
  image: node:11
  commands:
  - npm install -g codecov
  - yarn run gen-coverage
  - yarn run upload-coverage -- -F unit
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  depends_on:
  - unit tests node:11

- name: install node:12
  image: node:12
  commands:
  - node --version
  - npm --version
  - yarn --version
  - yarn install
  - yarn run bootstrap
  depends_on:
  - clone

- name: unit tests node:12
  image: node:12
  commands:
  - lerna run unit-test
  environment:
    BITGOJS_TEST_PASSWORD:
      from_secret: password
  depends_on:
  - install node:12

- name: upload coverage node:12
  image: node:12
  commands:
  - npm install -g codecov
  - yarn run gen-coverage
  - yarn run upload-coverage -- -F unit
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  depends_on:
  - unit tests node:12

...
