name: Publish @bitgo-beta
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  publish:
    name: Publish Beta Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install BitGoJS
        run: yarn install --with-frozen-lockfile

      - name: Configure Git & NPM
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout -b beta-$(git rev-parse --short HEAD)
          echo "email=${{ secrets.BETA_EMAIL }}" > .npmrc
          echo "@bitgo-beta:registry=https://registry.npmjs.org" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.BETA_TOKEN }}" >> .npmrc
          echo "//registry.npmjs.org/:always-auth=true" >> .npmrc
          
      - name: Prepare Beta
        run: |
          rm -rfd ./modules/web-demo
          rm -rfd ./modules/express
          npx ts-node ./scripts/prepare-beta.ts
      
      - name: Rebuild Beta
        run: yarn

      - name: Commit Local Changes
        run: git commit -am "Auto updated beta branch" --no-verify || echo "No changes to commit"

      - name: Lerna Publish 
        run: yarn lerna publish from-package --preid beta --dist-tag beta --force-publish --yes
